# Generated by Django 3.0.5 on 2022-06-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220605_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_buyer',
            new_name='is_yard',
        ),
    ]
