# Generated by Django 3.1 on 2022-06-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220602_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='created_date',
        ),
    ]
