# Generated by Django 3.1 on 2022-06-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_buyer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='supp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
            preserve_default=False,
        ),
    ]
