# Generated by Django 3.1 on 2022-06-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_buyer_supp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='supp_id',
            new_name='supp',
        ),
    ]
