# Generated by Django 3.1 on 2022-06-04 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_remove_buyer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='supp',
            new_name='supp_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
