# Generated by Django 3.0.5 on 2022-06-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220604_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alu', models.IntegerField()),
                ('zn', models.IntegerField()),
                ('aluc', models.IntegerField()),
                ('ss', models.IntegerField()),
                ('pb', models.IntegerField()),
                ('pvc', models.IntegerField()),
                ('fibre', models.IntegerField()),
                ('others1', models.IntegerField()),
                ('others2', models.IntegerField()),
                ('nm', models.IntegerField()),
                ('total', models.IntegerField()),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Yard')),
            ],
        ),
    ]
