# Generated by Django 3.0.5 on 2022-06-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_overheadcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overheadcost',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
