# Generated by Django 3.0.5 on 2022-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220611_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shortform', models.CharField(max_length=120)),
                ('rate', models.IntegerField()),
                ('misc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('details', models.CharField(max_length=120)),
                ('gradegrp', models.CharField(max_length=120)),
                ('misc', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shortform', models.CharField(max_length=120)),
                ('rate', models.IntegerField()),
                ('misc', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
