# Generated by Django 3.0.5 on 2022-06-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220614_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
    ]
