# Generated by Django 3.0.5 on 2022-06-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220617_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='totalc',
            new_name='totalp',
        ),
    ]
