# Generated by Django 3.0.5 on 2022-06-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20220617_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='alur',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='recovery',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='typeo',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
