# Generated by Django 3.2.6 on 2022-06-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20220619_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='alu',
            new_name='costc',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='aluc',
            new_name='metalcost',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='cha',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='cusi',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='extracost',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='extrasi',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='fibre',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='flux',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='nm',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='oh',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='oil',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='others1',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='others2',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='pb',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='pvc',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='ss',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='totalp',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='trans',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='vp',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='zn',
        ),
        migrations.AddField(
            model_name='grade',
            name='cost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.metal'),
            preserve_default=False,
        ),
    ]
