# Generated by Django 4.0.4 on 2022-06-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20220620_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='metalcost',
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc',
            field=models.IntegerField(max_length=20),
        ),
        migrations.CreateModel(
            name='metal_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metalcost', models.IntegerField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.grade')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.metal')),
            ],
        ),
        migrations.CreateModel(
            name='cost_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costc', models.IntegerField(default=0)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cost')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.grade')),
            ],
        ),
    ]
