# Generated by Django 3.2.6 on 2022-06-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_grade_cost_remove_grade_metal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metal_grade',
            old_name='metal',
            new_name='metaln',
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.metal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='ocost',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.cost'),
            preserve_default=False,
        ),
    ]
