# Generated by Django 3.2.6 on 2022-06-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20220624_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal_grade',
            name='metaln',
        ),
    ]
