# Generated by Django 3.2.6 on 2022-06-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_remove_metal_grade_metaln'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='ocost',
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc1',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc10',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc11',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc12',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc13',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc14',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc15',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc16',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc17',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc18',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc19',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc2',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc3',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc4',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc5',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc6',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc7',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc8',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metalc9',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln1',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln11',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln12',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln13',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln14',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln15',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln16',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln17',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln18',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln19',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln2',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln3',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln4',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln5',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln6',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln7',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln8',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='metaln9',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln',
            field=models.CharField(max_length=120),
        ),
    ]
