# Generated by Django 3.2.6 on 2022-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20220624_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='metalcn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='metalnn',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
