# Generated by Django 3.2.6 on 2022-06-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20220624_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='total',
        ),
    ]
