# Generated by Django 3.2.6 on 2022-06-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20220624_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='costc1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc19',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costc9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costcn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='costn1',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn10',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn11',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn12',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn13',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn14',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn15',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn16',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn17',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn18',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn19',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn2',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn20',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn3',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn4',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn5',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn6',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn7',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn8',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costn9',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AddField(
            model_name='grade',
            name='costnn',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
    ]
