# Generated by Django 3.2.6 on 2022-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20220625_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='costn1',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn10',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn11',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn12',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn13',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn14',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn15',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn16',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn17',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn18',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn19',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn2',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn20',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn3',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn4',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn5',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn6',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn7',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn8',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn9',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costnn',
            field=models.CharField(choices=[('Clearing Housing agency', 'Clearing Housing agency')], default=('Clearing Housing agency', 'Clearing Housing agency'), max_length=120),
        ),
    ]
