# Generated by Django 3.2.6 on 2022-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20220625_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='metalc',
            field=models.IntegerField(default=()),
        ),
    ]
