# Generated by Django 3.2.6 on 2022-06-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_auto_20220628_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='costn1',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn10',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn11',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn12',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn13',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn14',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn15',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn16',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn17',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn18',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn19',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn2',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn20',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn3',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn4',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn5',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn6',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn7',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn8',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn9',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costnn',
            field=models.CharField(choices=[(1, 'Clearing Housing agency'), (2, 'Demo'), (3, 'Demo Cost')], max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln1',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln10',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln11',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln12',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln13',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln14',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln15',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln16',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln17',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln18',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln19',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln2',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln20',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln3',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln4',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln5',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln6',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln7',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln8',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln9',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalnn',
            field=models.CharField(choices=[(2, 'Aluminium'), (4, 'Zn'), (5, 'Zinc')], default=(2, 'Aluminium'), max_length=120),
        ),
    ]
