# Generated by Django 3.1.12 on 2022-06-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_auto_20220628_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialmixp',
            name='yard',
        ),
        migrations.RemoveField(
            model_name='matmix',
            name='yard',
        ),
        migrations.RemoveField(
            model_name='metal_grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='mixmaterial',
            name='yard',
        ),
        migrations.RemoveField(
            model_name='overheadcost',
            name='yard',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='alur',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='yard',
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn1',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn10',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn11',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn12',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn13',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn14',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn15',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn16',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn17',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn18',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn19',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn2',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn20',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn3',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn4',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn5',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn6',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn7',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn8',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn9',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costnn',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln1',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln10',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln11',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln12',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln13',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln14',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln15',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln16',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln17',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln18',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln19',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln2',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln20',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln3',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln4',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln5',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln6',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln7',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln8',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln9',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalnn',
            field=models.CharField(choices=[(0, 1), (1, 1)], max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='cost_grade',
        ),
        migrations.DeleteModel(
            name='MaterialMixP',
        ),
        migrations.DeleteModel(
            name='MatMix',
        ),
        migrations.DeleteModel(
            name='metal_grade',
        ),
        migrations.DeleteModel(
            name='MixMaterial',
        ),
        migrations.DeleteModel(
            name='OverheadCost',
        ),
    ]
