# Generated by Django 3.1.12 on 2022-06-30 15:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_auto_20220630_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='eemail',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='emob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
