# Generated by Django 3.1.12 on 2022-06-30 16:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_auto_20220630_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='emob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
