# Generated by Django 3.1.12 on 2022-07-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_cost_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cost_grade',
        ),
    ]
