# Generated by Django 3.1.12 on 2022-07-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_auto_20220705_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.supplier')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.yard')),
            ],
        ),
    ]
