# Generated by Django 3.1.12 on 2022-07-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='metaln',
            field=models.CharField(choices=[('ALU', 'ALU'), ('Zn', 'Zn'), ('ZN', 'ZN')], default='Select', max_length=120, null=True),
        ),
    ]
