# Generated by Django 3.1.12 on 2022-07-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_auto_20220706_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='rate',
        ),
    ]
