# Generated by Django 3.1.12 on 2022-07-06 15:25

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_auto_20220706_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='grade',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='yard', chained_model_field='yard', on_delete=django.db.models.deletion.CASCADE, to='store.grade'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='yard',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='supplier', chained_model_field='supplier', on_delete=django.db.models.deletion.CASCADE, to='store.yard'),
        ),
    ]
