# Generated by Django 3.1.12 on 2022-07-06 15:52

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_auto_20220706_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='grade',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='yard', chained_model_field='yard', on_delete=django.db.models.deletion.CASCADE, to='store.grade'),
        ),
    ]
