# Generated by Django 3.1.12 on 2022-07-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_auto_20220706_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.grade'),
        ),
    ]
