# Generated by Django 3.1.12 on 2022-07-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_auto_20220707_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demo',
            new_name='Quality',
        ),
    ]
