# Generated by Django 3.2.13 on 2022-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0099_auto_20220710_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='costc',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=5),
        ),
    ]
