# Generated by Django 3.2.13 on 2022-07-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0101_alter_grade_costc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='costc1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc19',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc20',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costc9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costcn',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc19',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc20',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalc9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalcn',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='duty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw19',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw20',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalw9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='metalwc',
            field=models.FloatField(default=0, null=True),
        ),
    ]
