# Generated by Django 3.2.13 on 2022-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0102_auto_20220710_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='recovery',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
