# Generated by Django 3.2.13 on 2022-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_alter_grade_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='metaln',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln1',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln10',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln11',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln12',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln13',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln14',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln15',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln16',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln17',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln18',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln19',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln2',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln20',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln3',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln4',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln5',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln6',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln7',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln8',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln9',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalnn',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('ALU', 'ALU'), ('Zn', 'Zn'), ('Dm', 'Dm')], default=('Select', 0), max_length=120, null=True),
        ),
    ]
