# Generated by Django 3.2.13 on 2022-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0104_auto_20220713_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='misc',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='cost',
            name='name',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='cost',
            name='shortform',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn1',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn10',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn11',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn12',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn13',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn14',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn15',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn16',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn17',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn18',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn19',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn2',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn20',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn3',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn4',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn5',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn6',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn7',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn8',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costn9',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='costnn',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='details',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gradegrp',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln1',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln10',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln11',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln12',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln13',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln14',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln15',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln16',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln17',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln18',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln19',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln2',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln20',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln3',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln4',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln5',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln6',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln7',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln8',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metaln9',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='metalnn',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='misc',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='metal',
            name='misc',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='metal',
            name='name',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='metal',
            name='shortform',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='econtact',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='eemail',
            field=models.EmailField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ename',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
