# Generated by Django 3.2.13 on 2022-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_alter_quality_metalw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='rate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
